# Generated by Django 4.2.30 on 2026-06-18 12:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_jobseekeraccount_notification_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='company_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='founded_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='hq_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='logo_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='website_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='jobseekeraccount',
            name='followed_companies',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='session',
            name='employment_type',
            field=models.CharField(default='Full-time', max_length=50),
        ),
        migrations.AddField(
            model_name='session',
            name='experience_level',
            field=models.CharField(default='Mid-Level', max_length=50),
        ),
        migrations.AddField(
            model_name='session',
            name='location',
            field=models.CharField(blank=True, default='Remote', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='salary_range',
            field=models.CharField(default='Competitive', max_length=100),
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('saved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('seeker', models.ForeignKey(db_column='seeker_id', on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to='api.jobseekeraccount')),
                ('session', models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='api.session')),
            ],
            options={
                'db_table': 'saved_jobs',
                'unique_together': {('seeker', 'session')},
            },
        ),
    ]
