# Generated by Django 4.2.30 on 2026-06-20 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_company_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='agent_error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='agent_processing_status',
            field=models.CharField(default='completed', max_length=50),
        ),
        migrations.AddField(
            model_name='candidate',
            name='application_source',
            field=models.CharField(default='manual', max_length=50),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='last_notified_round_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
