# Generated by Django 4.2.30 on 2026-06-20 12:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_candidate_agent_error_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekeraccount',
            name='last_ats_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ResumeDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('template_id', models.CharField(default='modern', max_length=50)),
                ('content', models.JSONField(default=dict)),
                ('ats_score', models.FloatField(blank=True, null=True)),
                ('ats_report', models.JSONField(blank=True, null=True)),
                ('exported_pdf_path', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seeker', models.ForeignKey(db_column='seeker_id', on_delete=django.db.models.deletion.CASCADE, related_name='resume_drafts', to='api.jobseekeraccount')),
            ],
            options={
                'db_table': 'resume_drafts',
            },
        ),
        migrations.AddField(
            model_name='jobseekeraccount',
            name='active_resume_draft',
            field=models.ForeignKey(blank=True, db_column='active_resume_draft_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_seeker_account', to='api.resumedraft'),
        ),
    ]
