# Generated by Django 6.0.6 on 2026-06-26 14:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_jobseekeraccount_last_ats_score_resumedraft_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResumeVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.JSONField(default=dict)),
                ("ats_score", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "draft",
                    models.ForeignKey(
                        db_column="draft_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="api.resumedraft",
                    ),
                ),
            ],
            options={
                "db_table": "resume_versions",
            },
        ),
    ]
