# Generated by Django 6.0.6 on 2026-06-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_resume_version_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="fraudscanlog",
            name="detailed_checks",
            field=models.JSONField(default=dict),
        ),
    ]
