export const companies = [
  { id: "northwind", name: "Northwind", logoColor: "var(--google-blue)", industry: "Cloud Infrastructure", size: "1k–5k", location: "San Francisco, CA", founded: "2015", about: "Northwind builds the rails for modern cloud-native teams.", openings: 24, rating: 4.6 },
  { id: "lumen", name: "Lumen Labs", logoColor: "var(--google-green)", industry: "AI Research", size: "200–500", location: "Berlin, DE", founded: "2019", about: "We build models that reason, not just predict.", openings: 12, rating: 4.8 },
  { id: "atlas", name: "Atlas Pay", logoColor: "var(--google-red)", industry: "Fintech", size: "500–1k", location: "London, UK", founded: "2017", about: "Money movement for the next billion users.", openings: 31, rating: 4.4 },
  { id: "ember", name: "Ember Health", logoColor: "var(--google-yellow)", industry: "Healthcare", size: "50–200", location: "Boston, MA", founded: "2021", about: "A new operating system for primary care.", openings: 8, rating: 4.7 },
  { id: "vela", name: "Vela", logoColor: "var(--google-blue)", industry: "Design Tools", size: "50–200", location: "Remote", founded: "2020", about: "Collaborative design for distributed teams.", openings: 6, rating: 4.9 },
  { id: "nimbus", name: "Nimbus", logoColor: "var(--google-green)", industry: "Developer Tools", size: "10–50", location: "Toronto, CA", founded: "2022", about: "Faster builds. Calmer engineers.", openings: 4, rating: 4.5 },
];

export const jobs = [
  {
    id: "j1", title: "Senior Product Designer", company: "Vela", companyId: "vela", logoColor: "var(--google-blue)",
    location: "Remote · EU", type: "Full-time", remote: "Remote", salary: "$120k – $160k", posted: "2d ago",
    tags: ["Figma", "Design Systems", "Prototyping"],
    description: "Shape the next chapter of Vela's collaborative canvas. You'll own end-to-end design for a flagship surface used by millions of designers weekly.",
    responsibilities: ["Lead design for a flagship product area", "Partner with engineering on prototypes", "Evolve our design system"],
    requirements: ["5+ years product design experience", "Strong systems thinking", "Portfolio of shipped work"],
  },
  {
    id: "j2", title: "Staff ML Engineer", company: "Lumen Labs", companyId: "lumen", logoColor: "var(--google-green)",
    location: "Berlin, DE", type: "Full-time", remote: "Hybrid", salary: "€140k – €190k", posted: "1d ago",
    tags: ["PyTorch", "LLMs", "Distributed"],
    description: "Help us push the frontier of reasoning models. You'll work alongside researchers to ship training infrastructure at scale.",
    responsibilities: ["Design training pipelines", "Optimize multi-node training", "Mentor engineers"],
    requirements: ["7+ years ML engineering", "Experience with foundation models", "Strong systems background"],
  },
  {
    id: "j3", title: "Frontend Engineer", company: "Atlas Pay", companyId: "atlas", logoColor: "var(--google-red)",
    location: "London, UK", type: "Full-time", remote: "Hybrid", salary: "£85k – £115k", posted: "3d ago",
    tags: ["React", "TypeScript", "Next.js"],
    description: "Build the merchant dashboard used by tens of thousands of businesses across Europe.",
    responsibilities: ["Ship customer-facing features", "Improve performance", "Partner with design"],
    requirements: ["4+ years frontend experience", "Deep React knowledge", "Care for craft"],
  },
  {
    id: "j4", title: "Clinical Operations Lead", company: "Ember Health", companyId: "ember", logoColor: "var(--google-yellow)",
    location: "Boston, MA", type: "Full-time", remote: "On-site", salary: "$95k – $120k", posted: "5d ago",
    tags: ["Operations", "Healthcare", "Process"],
    description: "Lead operations across our growing clinic network.",
    responsibilities: ["Own clinical workflows", "Hire and coach managers", "Partner with product"],
    requirements: ["Healthcare ops experience", "Strong leadership track record"],
  },
  {
    id: "j5", title: "Platform Engineer", company: "Northwind", companyId: "northwind", logoColor: "var(--google-blue)",
    location: "San Francisco, CA", type: "Full-time", remote: "Hybrid", salary: "$160k – $210k", posted: "1w ago",
    tags: ["Kubernetes", "Go", "Infra"],
    description: "Build the multi-tenant platform powering Northwind's customer fleet.",
    responsibilities: ["Design platform primitives", "Improve developer experience"],
    requirements: ["Senior infra experience", "Kubernetes deep dive"],
  },
  {
    id: "j6", title: "DevRel Engineer", company: "Nimbus", companyId: "nimbus", logoColor: "var(--google-green)",
    location: "Remote · Americas", type: "Full-time", remote: "Remote", salary: "$110k – $140k", posted: "4d ago",
    tags: ["Content", "Open Source", "Talks"],
    description: "Help developers discover Nimbus through writing, talks and open source.",
    responsibilities: ["Write technical content", "Build sample projects", "Speak at events"],
    requirements: ["Engineering background", "Strong writing skills"],
  },
  {
    id: "j7", title: "Product Manager, Growth", company: "Atlas Pay", companyId: "atlas", logoColor: "var(--google-red)",
    location: "London, UK", type: "Full-time", remote: "Hybrid", salary: "£100k – £130k", posted: "2d ago",
    tags: ["Growth", "Experimentation"],
    description: "Drive Atlas Pay's activation and retention loops.",
    responsibilities: ["Run growth experiments", "Define funnel metrics"],
    requirements: ["3+ years PM experience", "Strong analytical skills"],
  },
  {
    id: "j8", title: "Brand Designer", company: "Vela", companyId: "vela", logoColor: "var(--google-blue)",
    location: "Remote", type: "Contract", remote: "Remote", salary: "$8k / mo", posted: "6d ago",
    tags: ["Brand", "Illustration", "Motion"],
    description: "Shape Vela's visual identity across web, product and events.",
    responsibilities: ["Own brand systems", "Create campaign visuals"],
    requirements: ["Strong brand portfolio", "Motion experience a plus"],
  },
];
